apiVersion: apps/v1
kind: Deployment
metadata:
  name: podchy-api-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: podchy-api
  template:
    metadata:
      labels:
        app: podchy-api
    spec:
      serviceAccountName: podchy-api
      containers:
        - name: podchy-api
          image: reqhiem/podchy-api:latest
          command: ["uvicorn", "config.asgi:application", "--host", "0.0.0.0", "--port", "8000"]
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: podchy-api-secret
          resources:
            requests:
              memory: "1Gi"
              cpu: "2"
            limits:
              memory: "2Gi"
              cpu: "4"