apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: podchy-api-serv
  labels:
    app: podchy-api
spec:
  selector:
    app: podchy-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000