apiVersion: v1
kind: ServiceAccount
metadata:
  name: podchy-api
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podchy-api-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec", "pods/log", "pods/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "exec"]
- apiGroups: ["batch", "extensions"]
  resources: ["jobs", "cronjobs", "jobs/status", "cronjobs/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: podchy-api-bind
subjects:
- kind: ServiceAccount
  name: podchy-api
  namespace: default
roleRef:
  kind: ClusterRole
  name: podchy-api-role
  apiGroup: rbac.authorization.k8s.io