apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: podchy-api-service
  labels:
    app: podchy-api
spec:
  type: NodePort
  selector:
    app: podchy-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80