apiVersion: apps/v1
kind: Deployment
metadata:
  name: podchy-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podchy-web
  template:
    metadata:
      labels:
        app: podchy-web
    spec:
      containers:
        - name: podchy-web
          image: reqhiem/podchy-web:latest
          command: ["nginx", "-g", "daemon off;"]
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: podchy-api-secret
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: podchy-web-service
  labels:
    app: podchy-web
spec:
  type: NodePort
  selector:
    app: podchy-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: podchy-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: podchy.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: podchy-web-service
                port:
                  number: 80