version: "3.9"

services:
  db:
    image: postgres:14.1-alpine
    container_name: podchy_db
    restart: always
    environment:
      POSTGRES_DB: podchy_db
      POSTGRES_USER: podchy
      POSTGRES_PASSWORD: podchy
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
  registry_data: