# Generated by Django 4.2.7 on 2023-11-10 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cpod",
            fields=[
                (
                    "cid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the cpod",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        choices=[("OWNER", "Owner"), ("INVITED", "Invited")],
                        default="OWNER",
                        help_text="Permission of the user",
                        max_length=20,
                    ),
                ),
                (
                    "cpod",
                    models.ForeignKey(
                        help_text="Cpod that the user has the permission",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.cpod",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User that has the permission",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cpod",
            name="users",
            field=models.ManyToManyField(
                help_text="Users that have access to the cpod",
                through="core.Permission",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
