# Generated by Django 4.2.7 on 2023-11-10 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cpod",
            options={
                "ordering": ["name"],
                "verbose_name": "Cpod",
                "verbose_name_plural": "Cpods",
            },
        ),
        migrations.CreateModel(
            name="FileCode",
            fields=[
                (
                    "fid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the file",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=100)),
                ("language", models.CharField(max_length=100)),
                ("value", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cpod",
                    models.ForeignKey(
                        help_text="Cpod that the file belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.cpod",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="User that created the file",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "File",
                "verbose_name_plural": "Files",
                "ordering": ["filename"],
            },
        ),
    ]
