# Generated by Django 4.2.7 on 2023-11-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cpod_options_filecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpod',
            name='language',
            field=models.CharField(default='python', help_text='Main programming language of the cpod', max_length=50),
        ),
    ]
