# Generated by Django 4.2.7 on 2023-11-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_filecode_filename_alter_filecode_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecode',
            name='value',
            field=models.TextField(blank=True, default='', help_text='Content of the file'),
        ),
    ]
